name: Freeze
on:
  branch_protection_rule:
    types: [created, deleted]

jobs:
  fail:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Try to fail
      run: echo "Hello World!"
